<!DOCTYPE html>
<html>
<head>
	<title>Hello Nicnic Website</title>
	<style>
		h1 {
			font-family: Arial, sans-serif;
			font-size: 36px;
			background-color: #F0E68C;
			padding: 20px;
			border-radius: 10px;
			box-shadow: 5px 5px 10px #888888;
			color: #333333;
			text-align: center;
		}
	</style>
</head>
<body>
	<h1>Hello Nicnic!</h1>
</body>
</html>
